language: go
sudo: required

services:
  - docker

before_install:
  - docker pull redis:alpine
  - docker run -p 6379:6379 -d redis:alpine

go:
  - "1.11"
  - master

script:
  - env GO111MODULE=on make test
